# Defaults
#exec = hyprctl dispatch submap global
#submap = global

source = hyprland/exec.conf
source = hyprland/binds.conf
source = hyprland/env.conf
source = hyprland/rules.conf
source = hyprland/colors.conf
source = hyprland/general.conf