$active = rgba(9ecaffff) 
$inactive = rgba(2b3139ff)

$text_color = rgba(d1e4ffFF)

$entry_background_color = rgba(001d3611)
$entry_border_color     = rgba(8b919b55)
$entry_color            = rgba(d1e4ffFF)

$font_family            = Adwaita Sans
$font_family_clock      = Noto Sans
$font_material_symbols  = MesloLGS Nerd Font

$background_image = /home/jared/Wallpapers/xelyx3.jpg

