##############################
### WINDOWS AND WORKSPACES ###
##############################

windowrule {
    # Ignore maximize requests from all apps. You'll probably like this.
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

# Hyprland-run windowrule
windowrule {
    name = move-hyprland-run

    match:class = hyprland-run

    move = 20 monitor_h-120
    float = yes
}

windowrule = idle_inhibit fullscreen, match:fullscreen true

windowrule {
	name = float
	match:class = nm-connection-editor|blueman-manager|org.pulseaudio.pavucontrol

	float = yes
}

layerrule {
	name = waybar
	match:namespace = waybar
	
	blur = yes
	ignore_alpha = 0.2
}

layerrule {
	name = rofi
	match:namespace = rofi
	
	blur = yes
	ignore_alpha = 0.2
}

layerrule {

	name = swaync
	match:namespace = swaync-control-center|swaync-notification-window
	
	blur = yes
	ignore_alpha = 0.2
}

layerrule {

	name = Wlogout
	match:namespace = logout_dialog
	
	blur = yes
	blur_popups = yes
	dim_around = yes
}

windowrule {
    name = opacity
    match:class = org.gnome.Nautilus|nm-connection-editor|org.pulseaudio.pavucontrol|codium|org.kde.dolphin|org.kde.polkit-kde-authentication-agent-1|polkit-gnome-authentication-agent-1

    opacity = 0.80
}

windowrule {
    name = opacity-fullscreen
    match:class = codium
    match:fullscreen = true

    opacity = 1
}

