$active = rgba({{colors.primary.default.hex_stripped}}ff) 
$inactive = rgba({{colors.inverse_on_surface.default.hex_stripped}}ff)

$text_color = rgba({{colors.primary_fixed.default.hex_stripped}}FF)

$entry_background_color = rgba({{colors.on_primary_fixed.default.hex_stripped}}11)
$entry_border_color     = rgba({{colors.outline.default.hex_stripped}}55)
$entry_color            = rgba({{colors.primary_fixed.default.hex_stripped}}FF)

$font_family            = Adwaita Sans
$font_family_clock      = Noto Sans
$font_material_symbols  = MesloLGS Nerd Font

$background_image = {{image}}

